//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace taskcrude.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int Employee_id { get; set; }
        [Required(ErrorMessage = "First Name is required.")]
        [RegularExpression("[A-Za-z]+", ErrorMessage = "Only alphabets.!")]
        public string f_name { get; set; }

        [Required]
        [EmailAddress(ErrorMessage = "Invalid Email.!")]
        public string email { get; set; }

        [Required]
        [RegularExpression("[0-9]+", ErrorMessage = "Only numbers.!")]
        public string phone_number { get; set; }

        [Required]
        public string address { get; set; }

        [Required]
        public int state_id { get; set; }

        [Required]
        public int city_id { get; set; }

        public virtual city city { get; set; }
        public virtual state state { get; set; }
    }
}
